language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - wget https://github.com/libgit2/libgit2/archive/v0.22.3.tar.gz
  - tar -xzvf v0.22.3.tar.gz
  - cd libgit2-0.22.3/
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - cmake --build .
  - sudo make install
  - cd $HOME/gopath/src/github.com/ukitazume/ey-berks
script: 
  - go test ./...
